[package]
name = "samd-i2s"
version = "0.1.0"
authors = ["Ian Rees <ian.rees@gmail.com>"]
edition = "2018"
keywords = ["no-std", "arm", "cortex-m", "embedded-hal", "samd", "atsamd", "samd21"]

[dependencies]
cortex-m = "~0.6"

[dependencies.atsamd-hal]
version = "~0.9"
default-features = false

[dependencies.defmt]
git = "https://github.com/knurling-rs/defmt"
# Must be the same revision as probe-run's defmt-decoder and defmt-elf2table
rev = "a6dc0904872cd3f4aee5125dffc17723df3c9393"

[dependencies.defmt-rtt]
git = "https://github.com/knurling-rs/defmt"
# Must be the same revision as probe-run's defmt-decoder and defmt-elf2table
rev = "a6dc0904872cd3f4aee5125dffc17723df3c9393"

[features]
samd21 = []
samd21g18a = ["samd21", "atsamd-hal/samd21g18a", "defmt-default"]

defmt-default = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []